version: '3.9'
services:
  web1:
    restart: on-failure
    build: ./web
  web2:
    restart: on-failure
    build: ./web
  nginx:
    build: ./nginx
    ports:
    - '80:80'
    depends_on:
    - web1
    - web2