version: '3.9'
services:
  web1:
    restart: on-failure
    build: ./web
    env_file:
      - ./web/.env
    environment:
      - NODE_ENV=production
  web2:
    restart: on-failure
    build: ./web
    env_file:
      - ./web/.env
    environment:
      - NODE_ENV=production
  nginx:
    build: ./nginx
    ports:
    - '80:80'
    depends_on:
    - web1
    - web2